### ISSUE TITLE
CSVs aren't being parsed correctly as per the documentation

### ISSUE THREAD

**Issue by bjdooi** [mafintosh/csv-parser#101]
* Operating System: OS X El Capitan 10.11.6
* Node Version: v11.0.0
* NPM Version: 6.4.1
* csv-parser Version: 2.1.0 

### Expected Behavior
Following the example in the README.md:

Suppose you have a CSV file data.csv which contains the data:

```
NAME, AGE
Daffy Duck, 24
Bugs Bunny, 22
```
It could then be parsed, and results shown like so:

```
const csv = require('csv-parser')
const fs = require('fs')
const results = [];

fs.createReadStream('data.csv')
  .pipe(csv())
  .on('data', results.push)
  .on('end', () => {
    console.log(results);
    // [
    //   { NAME: 'Daffy Duck', AGE: 24 },
    //   { NAME: 'Bugs Bunny', AGE: 22 }
    // ]
  });
```

### Actual Behavior
I created a file data.csv in the same directory as the node file I'm running.

My code is copied and pasted from above:

```
const csv = require('csv-parser')
const fs = require('fs')
const results = [];

fs.createReadStream('data.csv')
  .pipe(csv())
  .on('data', results.push)
  .on('end', () => {
    console.log(results);
    // [
    //   { NAME: 'Daffy Duck', AGE: 24 },
    //   { NAME: 'Bugs Bunny', AGE: 22 }
    // ]
  });
```

However the result to console.log is:
`[]`

I know I'm accessing the correct thing because I then modified the code to this:

```
const csv = require('csv-parser')
const fs = require('fs')
const results = [];

fs.createReadStream('data.csv')
  .pipe(csv())
  .on('data', (results) => {
    console.log(results);
  })
  .on('end', () => {
    console.log(results);
    // [
    //   { NAME: 'Daffy Duck', AGE: 24 },
    //   { NAME: 'Bugs Bunny', AGE: 22 }
    // ]
  });
```

Output to console.log:
```
Row { NAME: 'Daffy Duck', ' AGE': ' 24' }
Row { NAME: 'Bugs Bunny', ' AGE': ' 22' }
[]
```

The other header is getting turned into a string value and it's not being picked up. The empty array still persists

### How Do We Reproduce?
Run the example

**Comment by shellscape** [comment]
@bjdooi thanks for stopping in. Change your `data` handler to:

```js
  .on('data', (d) => {
    results.push(d);
  })
```

Probably a context issue passing `results.push` as the handler fn. Feel free to submit a PR to the README to update this if you're up for it.

**Comment by bjdooi** [comment]
Thank you for the response, however there still is an issue with the returned results array. Instead of getting:
```
[
   { NAME: 'Daffy Duck', AGE: 24 },
   { NAME: 'Bugs Bunny', AGE: 22 }
 ]
```

My code instead returns something different
```
const csv = require('csv-parser')
const results = [];

fs.createReadStream('data.csv')
  .pipe(csv())
  .on('data', (d) => {
    results.push(d);
  })
  .on('end', () => {
    console.log(results);
    console.log(results[0].NAME);
    console.log(results[0].AGE);
  });
```

console.log output:
```
[ Row { NAME: 'Daffy Duck', ' AGE': ' 24' },
  Row { NAME: 'Bugs Bunny', ' AGE': ' 22' } ]
Daffy Duck
undefined
```

From this I can tell that spaces in the .csv file aren't being read/picked up correctly. If I change my data.csv to this:
```
NAME,AGE
Daffy Duck,24
Bugs Bunny,22
```

Then the output becomes correct, and I can access AGE:
```
[ Row { NAME: 'Daffy Duck', AGE: '24' },
  Row { NAME: 'Bugs Bunny', AGE: '22' } ]
Daffy Duck
24
```

So whitespace isn't being run over correctly. Should I create another issue for this? I'll also send in the PR for that README.md update, but I think the whitespace handling is more important.

**Comment by shellscape** [comment]
By default anything between commas is considered part of the value. That's a CSV spec thing. If you'd like to update the README to reflect corrected values as well, that's cool.

**Comment by bjdooi** [comment]
Thank you for making the intended functionality of the package clear to me; I'll make sure to include the corrected values in the PR.

**Comment by mishawagon** [comment]
This helped me too, but I don't get why the main doc is not updated to include this? The way it lists results getting pushed results in an empty object

**Comment by DanielAsher** [comment]
This really should be sorted out as I wasted a good amount of time using the example code on npmjs.
