### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by alessioalex** [mafintosh/csv-parser#11]
I've tried out this module with some sample data and I get no output: http://www.briandunning.com/sample-data/

**Comment by hmalphettes** [comment]
@mafintosh When I exported an xlsx file from MS Excel on Macos I ended up with such a csv file.
Here is a PR to support this case: https://github.com/mafintosh/csv-parser/pull/19

**Comment by mafintosh** [comment]
Should be fixed in 1.5.1 thanks to @hmalphettes

**Comment by hmalphettes** [comment]
Thanks for pulling it in so quickly. Cheers everyone!
