### ISSUE TITLE
Adding header and skipLines does not skip any lines

### ISSUE THREAD

**Issue by combizs** [mafintosh/csv-parser#110]
* Operating System: macOs Sierra v10.12.6
* Node Version: v8.9.1
* NPM Version: 6.1.0
* csv-parser Version: 4.0.1

### Expected Behavior
```gherkin
Given header option is defined
When rows are parsed
Then modified header row should be ignored
```

### Actual Behavior
```gherkin
Given header option is defined
When rows are parsed
Then modified header is included as first row
```

### How Do We Reproduce?
Pass in header option, `{headers: ['n', 'a'], skipLines: 2}`,
and use file contents:
```
NAME,AGE
Daffy Duck,24
Bugs Bunny,22
Marvin the Martian,101
```
then the result will be:
```
[
  { n: 'NAME', a: 'AGE'},
  { n: 'Daffy Duck', a: '24'},
  { n: 'Bugs Bunny', a: '22'}
  { n: 'Marvin the Martian', a: '101'}
]
```

but should be:
```
[
  { n: 'Bugs Bunny', a: '22'}
  { n: 'Marvin the Martian', a: '101'}
]
```

**Comment by shellscape** [comment]
This test covers `skipLines` https://github.com/mafintosh/csv-parser/blob/master/test/test.js#L420. If this isn't behaving as intended, please submit a PR with a failing test and we'll have a look at triaging it. Would also review a PR that resolved the issue to expectation.

**Comment by combizs** [comment]
Updated my initial issue to reflect on the expected behavior of adding a header; if a header exists, the keys will be replaced with that of the header and the header will also be emitted.

That being said, if the options contain `header` and `skipLines`, both should function; will look at test files tomorrow.

**Comment by combizs** [comment]
@shellscape, I want to put in a PR with the [fix](https://github.com/mafintosh/csv-parser/pull/111), but I need to know what the intended behavior is when the following option is passed in?

`{ headers: ['n', 'a'], skipLines: 2 }`

is it supposed be:
```
[
  { n: 'Bugs Bunny', a: '22'}
  { n: 'Marvin the Martian', a: '101'}
]
```
or
```
[
  { n: 'NAME', a: 'AGE'},
  { n: 'Marvin the Martian', a: '101'}
]
```
