### ISSUE TITLE
README.md example on npmjs.com is out of date

### ISSUE THREAD

**Issue by ayliao** [mafintosh/csv-parser#112]
Hi there! 

I was wondering if there were any plans to publish a new minor version of this package in order to update the docs on npmjs.com? I just started using this package, and I was confused when running the  Usage example gave me two undefineds.

From looking through this repo, it looks like the docs have already been remedied in [this PR](https://github.com/mafintosh/csv-parser/pull/103) and a new version just needs to be published so that the changes are reflected.

Cheers!

**Comment by shellscape** [comment]
A new version will be published.
