### ISSUE TITLE
how to remove white space in start and last of string 

### ISSUE THREAD

**Issue by bipinshukla** [mafintosh/csv-parser#113]
hello guys, i go through document but have n't find any solution 
        [ Row {
            bankcustomers_id: '154491',
            customerid: '154491',
            title: 'MR ',
            firstname: 'Santa          ',
            lastname: 'Clause                             ',
            dob: '25-Dec-30',
            mobileno: '07900 1234567  ',
            emailid: 'santa-clause@northpole                       ',
            housenumber: '5',
            address1: '5 North Street                          ',
            address2: 'Pole                                    ',
            address3: 'London                                  ',
            address4: '                                        ',
            address5: '                                        ',
            postcode: 'DY3 11X     
                                                                                                                            ' }]
above is output is product by csv parser now my problem is that is there any provision to remove this white space at start and last of  charater or  consecutive ,, .and how i can get single column value .how i can remove all mention this is there anybody help me out with this

**Comment by shellscape** [comment]
You can use the [`mapValues`](https://github.com/mafintosh/csv-parser#mapvalues) function to do that. Please read the README.

**Comment by bipinshukla** [comment]
@shellscape can you give me example of all provide condition should i use regular expression

**Comment by bipinshukla** [comment]
@shellscape i want ot insert each row into data base so how i can read row on this function 
         .on('data', (data) =>{
            //    console.log(data)
              results.push(data)
            })

**Comment by shellscape** [comment]
@bipinshukla please use the "edit" feature of a post rather than posting consecutive replies on Github. I'm sorry, but I don't provide individual user support (and this really isn't a support forum for miscellaneous programming questions). Perhaps another user will provide that info to you, but those are rather basic programming questions unrelated to this module that you should research/learn on sites that cover those types of things (StackOverflow, etc).
