### ISSUE TITLE
npmjs readme demo code minor error

### ISSUE THREAD

**Issue by JaosnHsieh** [mafintosh/csv-parser#119]
Documentation Is:

- [ ] Missing
- [ ] Needed
- [ X ] Confusing
- [ ] Not Sure?

### Please Explain in Detail...
current npm [page usage demo code](https://www.npmjs.com/package/csv-parser#usage)

```js
const csv = require('csv-parser')
const fs = require('fs')
const results = [];
 
fs.createReadStream('data.csv')
  .pipe(csv())
  .on('data', results.push)
  .on('end', () => {
    console.log(results);
    // [
    //   { NAME: 'Daffy Duck', AGE: 24 },
    //   { NAME: 'Bugs Bunny', AGE: 22 }
    // ]
  });

```

`.on('data', results.push)` leads to results equals `[]` due to context lost.
### Your Proposal for Changes

same as github readme demo code

```js
const csv = require('csv-parser')
const fs = require('fs')
const results = [];

fs.createReadStream('data.csv')
  .pipe(csv())
  .on('data', (data) => results.push(data))
  .on('end', () => {
    console.log(results);
    // [
    //   { NAME: 'Daffy Duck', AGE: '24' },
    //   { NAME: 'Bugs Bunny', AGE: '22' }
    // ]
  });

```

**Comment by shellscape** [comment]
NPM contains a copy of the README from last version published. Occasionally the README for the module will be updated but no new version published when there are no code changes. It's not great, but it happens. That's one of the reasons that NPM contains a link back to the repo the module lives in. I just added some additional documentation, and when I make my way through the other issues, I'll publish a patch bump to update NPM.
