### ISSUE TITLE
--only-parse=column1,column2

### ISSUE THREAD

**Issue by maxogden** [mafintosh/csv-parser#12]
if specified, dont parse columns that arent in the list

**Comment by hmalphettes** [comment]
This is supported now although with the reverse api: `--remove=column3,column4`:
https://github.com/mafintosh/csv-parser/pull/55

I am not convinced that remove is always the best option so let me know if you want a PR with `--only-parse`

**Comment by shellscape** [comment]
Closing citing `--remove` and `mapHeaders` capabilities.
