### ISSUE TITLE
Uncaught TypeError: fs.createReadStream is not a function

### ISSUE THREAD

**Issue by agorfine** [mafintosh/csv-parser#120]
* Operating System: macOS Mojave v 10.14.3
* Node Version: v11.0.0
* NPM Version: 6.4.1
* csv-parser Version: 2.1.0

### Expected Behavior
Use documentation to parse local csv file, and console.log results.

### Actual Behavior
Receiving error "Uncaught TypeError: fs.createReadStream is not a function"

### How Do We Reproduce?

I am using React, and I implemented the following code after installing the package
```
componentDidMount() {
    const csv = require('csv-parser')
    const fs = require('fs')
    const results = []
    fs.createReadStream('./Data.csv')
      .pipe(csv(['firstName','lastName','email','birthday','homePhone','workPhone','customerType']))
      .on('data', (data) => results.push(data))
      .on('end', ()=>{
        console.log(results)
      })
  }
```

**Comment by shellscape** [comment]
This module doesn't interact with, hook, nor manipulate the `require` chain. (Hint: React does though!) The error is going to lie elsewhere. If you encounter an error where the stack trace points back to this module, please open a new issue.

**Comment by DebaPrasad14** [comment]
I am getting the same error while using this in vue.
