### ISSUE TITLE
mapHeaders not working

### ISSUE THREAD

**Issue by rahul3103** [mafintosh/csv-parser#122]
* Operating System: OS X (Mojave 10.14.3)
* Node Version: v10.15.1
* NPM Version: 6.4.1
* csv-parser Version: 2.1.0

```
  fs.createReadStream(path.join(__dirname, 'data/data.csv'))
  .pipe(
    csv({
      mapHeader: ({ header, index }) => header.toLowerCase()
    })
  )
  .on('headers', headers => headers.map(head => head.toLowerCase()))
  .on('data', data => {
    console.log(data);
  });
```
`Row {ID: "543211", Name: "Kathyrn Elser  ", LIMIT_BAL: "20000", SEX: "2", EDUCATION: "2", …}`
### Expected Behavior

I thought all the key(header) will be in lowercase but that 's not happening.
`Row {id: "543211", name: "Kathyrn Elser  ", limit_bal: "20000", sex: "2", education: "2", …}`

### Actual Behavior
`Row {ID: "543211", Name: "Kathyrn Elser  ", LIMIT_BAL: "20000", SEX: "2", EDUCATION: "2", …}`

### How Do We Reproduce?
Just run the above code with csv file.

**Comment by shellscape** [comment]
Our tests for this feature are working properly: https://github.com/mafintosh/csv-parser/blob/master/test/mapHeaders.test.js _(Note that the tests were recently reorganized but that this test has existed for some time now)_

**Comment by SimonSimCity** [comment]
@rahul3103 you forgot the `s` in the end of the option. The option is named `mapHeaders` 😉

**Comment by shellscape** [comment]
Good catch, typo def looks to be the cause here.
