### ISSUE TITLE
index.d.ts is not found when installing via npm/yarn

### ISSUE THREAD

**Issue by BrianBorge** [mafintosh/csv-parser#123]
When installing release `2.1.0` via npm or yarn, `index.d.ts` is missing.  I don't know what is needed to push packages to npm, but when I look at the package.json file for `csv-parser`, `index.d.ts` is not included in the list of files:

```
// csv-parser's package.json
//..
"main": "index.js",
  "files": [
    "bin/csv-parser",
    "index.js"
  ],
//..
```

I got around the issue by telling yarn to install the master branch of this repo as the current release (2.1.0) does not include `index.d.ts`.

* Operating System: macOS 10.14.14
* Node Version: 8.10.0
* NPM Version: 5.6.0
* csv-parser Version: 2.1.0

### Expected Behavior

I expect `index.d.ts` to be included in contents of `node_modules/csv-parser` for use with TypeScript

### Actual Behavior

The contents of `node_modules/csv-parser` does not include `index.d.ts`

### How Do We Reproduce?

`yarn add csv-parser` and then inspect contents of `node_modules/csv-parser`

**Comment by shellscape** [comment]
Thanks for reporting this. This was resolved some time ago and will be resolved with the next version publish. https://github.com/mafintosh/csv-parser/blob/ead4c1f3a14dbdad961231f3685307e78a03b07e/package.json#L17-L20
