### ISSUE TITLE
What is Row from the result stream?

### ISSUE THREAD

**Issue by RichieRunner** [mafintosh/csv-parser#126]
* Operating System:
* Node Version:
* NPM Version:
* csv-parser Version:

### How Do We Reproduce?
I used the sample from here:

```javascript
const csv = require('csv-parser')
const fs = require('fs')
const results = [];
 
fs.createReadStream('data.csv')
  .pipe(csv())
  .on('data', (data) => results.push(data))
  .on('end', () => {
    console.log(results);
    // [
    //   { NAME: 'Daffy Duck', AGE: '24' },
    //   { NAME: 'Bugs Bunny', AGE: '22' }
    // ]
  });
```
But what is row? I don't need it in my result output.

![image](https://user-images.githubusercontent.com/20289967/54002308-f9e84680-4102-11e9-936c-ed09863801f4.png)

**Comment by shellscape** [comment]
My dude, this is nowhere near a proper issue. I would recommend reading up on some Node.js fundamentals to understand what you're seeing in your console.

**Comment by RichieRunner** [comment]
Just shut this thing down if you're gonna be this toxic.
