### ISSUE TITLE
First row's header quoted

### ISSUE THREAD

**Issue by khairulashraff** [mafintosh/csv-parser#131]
* Operating System: Docker node:8-slim
* Node Version: 8.16
* NPM Version: 6.4.1
* csv-parser Version: 2.3.0

### Expected Behavior
Data of
```
col1,col2,col3
a,2,foobar
```
becomes:
```
[
	Row {
		col1: 'a',
		col2: '2',
		col3: 'foobar'
	}
]
```

### Actual Behavior
```
[
	Row {
		'﻿col1': 'a',
		col2: '2',
		col3: 'foobar'
	}
]
```
Notice how the first column's header has a single quote around it: `'col1'`.

### How Do We Reproduce?
File was created from Excel (using 16.24 via Office 365 subs). File has been checked with text editor and confirmed does not have a quote around the first column's header.

[test-csv-parser.csv.zip](https://github.com/mafintosh/csv-parser/files/3176174/test-csv-parser.csv.zip)

### Code
```
const csv = require('csv-parser')
const fs = require('fs')
const results = [];

fs.createReadStream('test-csv-parser.csv')
  .pipe(csv())
  .on('data', (data) => results.push(data))
  .on('end', () => {
    console.log(results);
  });
```

This may be related with #127 .

**Comment by shellscape** [comment]
Thanks for putting together a zip file, but almost no one will trust a zip to download these days. Please use test repositories or a [gist](https://gist.github.com) in the future. 

Quoted property names shouldn't matter. `{ 'foo': 'bar' }` is equivalent to `{ foo: 'bar' }`. If you have a specific use-case whereby the quoted property name is causing errors, please share that and we'll reopen.

**Comment by daytonmills** [comment]
I have this issue... When trying to use the .create() function from sequelize...

```
Sale.create({
   invoice: customer.invoice,
...
```
when I console log my customer object, I can see invoice in quotations as 'invoice'.

So customer.invoice is quoted and returns undefined, but every other key is fine as its unquoted.

**Comment by daytonmills** [comment]
I managed to get around this by defining my headers in the csv options instead and removing them from the csv.

**Comment by nickpainter** [comment]
@shellscape @daytonmills I discovered that this issue can be reproduced by simply setting the encoding to UTF-8-BOM within notepad++.  This is also the format that excel uses when saving csv files by default.  A workaround is to manually change the encoding to UTF-8.

@shellscape - Any chance that this issue can be re-opened?  It seems to be a very legitimate issue.

**Comment by shellscape** [comment]
@nickpainter see: https://github.com/mafintosh/csv-parser/issues/140#issuecomment-516023276

**Comment by nickpainter** [comment]
> @daytonmills I discovered that this issue can be reproduced by simply setting the encoding to UTF-8-BOM within notepad++. This is also the format that excel uses when saving csv files by default. A workaround is to manually change the encoding to UTF-8.

For future people stumbling on my comment.  https://github.com/mafintosh/csv-parser#byte-order-marks documents the issue well and contains a solution.

**Comment by butterprim** [comment]
FWIW, for anyone who is on the same boat as me who couldn't use the package `strip-bom-stream` because of commonjs, I am able to get around the issue by replacing the headers through options:
```
const csv = require('csv-parser');

const results = [];
fs.createReadStream(`./${path}`)
    .pipe(csv({
        mapHeaders: (({ header }) => {
            if (header.charCodeAt(0) === 0xFEFF) {
                header = header.substr(1);
            }
            return header;
        })
    }))
    .on('data', (data) => {
        results.push(data);
    })
    .on('end', () => {
        resolve(results);
    });
```
Thanks to this piece of [code](https://gist.github.com/antic183/619f42b559b78028d1fe9e7ae8a1352d) I saw.

**Comment by FaizaanFazal** [comment]
For me .trim() worked, example:
  const sanitizedRecord = Object.keys(record).reduce((acc, key) => {
              const trimmedKey = key.trim();
              acc[trimmedKey] = record[key]; 
              return acc;
            }, {} as Record<string, any>);
