### ISSUE TITLE
Uncaught Error: Cannot find module 'csv-parser' Require stack

### ISSUE THREAD

**Issue by burakkp** [mafintosh/csv-parser#134]
* Operating System:Windows 10
* Node Version: v.10.16.0
* NPM Version: ^6.9.0
* csv-parser Version: ^2.3.0

I develop electron app on Windows. I implemented 'csv-parser' and I am reading also csv file. This application working very well on development but I get build and control the production I get this error.

![Untitled](https://user-images.githubusercontent.com/5391838/59228105-45fdc800-8bd7-11e9-996c-bcd13deb2635.png)

**Comment by shellscape** [comment]
Doesn't look like that's a problem with this module. I'd suggest asking in Electron forums.

**Comment by burakkp** [comment]
> Doesn't look like that's a problem with this module. I'd suggest asking in Electron forums.

Ok. Thank you.
