### ISSUE TITLE
Lower required node version?

### ISSUE THREAD

**Issue by richardhinkamp** [mafintosh/csv-parser#148]
* Operating System: Ubuntu 18.04 LTS
* Node Version: 8.10.0
* NPM Version: yarn 1.19.1
* csv-parser Version: 2.3.1

### Expected Behavior / Situation
Can install 2.3.1

### Actual Behavior / Situation
Cannot install 2.3.1:
error csv-parser@2.3.1: The engine "node" is incompatible with this module. Expected version ">= 8.16.0". Got "8.10.0"

### Modification Proposal
Is 8.16 really needed? I have some places where I'm stuck on the node version of Ubuntu 18.04 LTS which is 8.10.0. I did not expect 2.3.0 to 2.3.1 to change the required node version. Maybe node 8 is needed, but is 8.x not enough? Would you consider lowering the required version so it can be installed on node 8.10.0 (and maybe other versions for other operating systems)? If 8.16 is really needed, could you explain what change between 8.10 and 8.16 this regards?

Thanks!

**Comment by shellscape** [comment]
Thanks for opening an issue :beer: Node v8 is in maintenance LTS (https://nodejs.org/en/about/releases/) so it's not unreasonable to expect people using that to at the very least be up to date on that maintenance version. There's also a degree of responsibility as the latest minor will not only have feature-forward updates, but also security fixes. You're also going to be kind of boned when the majority of the ecosystem drops Node 8 support after Dec 31st 2019. I believe it's a good thing this module was able to bring that to your attention, but at this time I'm not in favor of modifying the engines requirement.
