### ISSUE TITLE
Support of line comma suffix was removed.

### ISSUE THREAD

**Issue by shlomo666** [mafintosh/csv-parser#155]
* Operating System: MacOS, Linux
* Node Version: 8.5.0
* NPM Version: 5.3.0
* csv-parser Version: 2.3.1

### Expected Behavior
**Used to read files just fine** when files had "," at the end of every line, back in my old version 1.12.0.

### Actual Behavior
Creating a map of values where the keys are 0-N (numbers of columns).

### How Do We Reproduce?
File:
```
a1,b1,c1,
a2,b2,c2,
```

code:
```
const csv = require('csv-parser');
const fs = require('fs');
const results = [];

fs.createReadStream('b')
  .pipe(csv({ headers:["a", "b", "c"],  } ))
  .on('data', (data) => results.push(data))
  .on('end', () => {
    console.log(results);
    console.log(results.length);
  });
```

Result in v2.3.1:
```
[ { '0': 'a1', '1': 'b1', '2': 'c1', '3': '' },
  { '0': 'a2', '1': 'b2', '2': 'c2', '3': '' } ]
```

Result in v1.12.0:
```
[ Row { a: 'a1', b: 'b1', c: 'c1' },
  Row { a: 'a2', b: 'b2', c: 'c2' } ]
```

**Comment by shellscape** [comment]
The [CSV Specification](https://tools.ietf.org/html/rfc4180) does not specifically address trailing commas and doesn't specify that they should be dropped. Empty/missing values between or after commas are treated as an empty column of data.

**Comment by shlomo666** [comment]
Correct. Thanks.

**Comment by mapo-job** [comment]
Having the same issue, is there a way to remove the empty header/value?
I try this but it does not work:
` delete record[''];`
Also I get different result when running on different os node version.

Example: 
```
//data.csv content
//NAME,AGE,
//Daffy Duck,24,
//Bugs Bunny,22,

const csv = require('csv-parser')
const fs = require('fs')
const results = [];

fs.createReadStream('data.csv')
.pipe(csv({mapValues: ({ header, index, value }) => isNaN(+value)?value:+value}))
.on('data', (data) => results.push(data))
.on('end', () => {
  console.log(JSON.stringify(results[0], null, 2));
});
```
Linux (Red Hat 4.8.5-36)  node version v12.16.1 result:
`{ "NAME": "Daffy Duck", "AGE": 24, "": 0}`

Windows 10 node version v12.16.1 result:
`{ "NAME": "Daffy Duck", "AGE": 24}`
