### ISSUE TITLE
push null should be sent when file is read completly

### ISSUE THREAD

**Issue by pguijarr** [mafintosh/csv-parser#156]
* Operating System: Linux
* Node Version: v12.13.0
* NPM Version: 6.12.0
* csv-parser Version: 2.3.2

### Expected Behavior
It should send null chunk when file is finished for a new pipe.

### Actual Behavior
the next pipe cannot know when csv is finished completely, there is not difference between the last element or one in the middle.

### How Do We Reproduce?
Using a new pipe after the csv_parser and try to find the last element.

**Comment by shellscape** [comment]
Please reference the example in the README for how to cache rows/records as they are streamed. It's not the stream's ("pipe") job to let you know what the last element is.
