### ISSUE TITLE
Update documentation for skipping lines

### ISSUE THREAD

**Issue by conartist6** [mafintosh/csv-parser#165]
It seems that the `skipLines` option was replaced with `from` and `fromLine` options, however the documentation was not updated.

**Comment by LMJayasundara** [comment]
How to use these from and fromLine option.
I can not find please help me ❤

**Comment by conartist6** [comment]
Nope looks like I was wrong. `skipLines` is the new way, and I guess the code matches the docs now.

**Comment by LMJayasundara** [comment]
Can you give me some idea about this

https://github.com/mafintosh/csv-parser/issues/185#issue-743889289
