### ISSUE TITLE
First key in each result is wrapped in single quotes.

### ISSUE THREAD

**Issue by freesh** [mafintosh/csv-parser#166]
* Operating System: OSX
* Node Version: 12.12
* NPM Version: 6.13.4
* csv-parser Version: 2.3.2

### Expected Behavior

Importing CSV file and all keys without single quotes.

```
{
    title: 'This is a title',
    theme: 'Work-Life-Balance ',
    region: 'Berlin',
  }
```

### Actual Behavior

Importing CSV file. But console.log shows me the first key of each record is wrapped in single quotes.

```
{
    '﻿title': 'this is a title',
    theme: 'Work-Life-Balance ',
    region: 'Berlin',
  }
```

### How Do We Reproduce?
 
This is my data.csv

```
title;theme;region
myTitle;Work-Life-Balance;Berlin
myTitle2;Work-Life-Balance;Berlin
```

This is the code:

```javascript
const csv = require('csv-parser');
const fs = require('fs');
const results = [];

const indexCsv = () => {
    fs.createReadStream('data.csv')
        .pipe(csv({ 
            separator: ';',
            quote: '"'
            }
        ))
        .on('data', (data) => results.push(data))
        .on('end', async () => {
            console.log(results);
            // ....
        })
}

indexCsv();
```

**Comment by mattmiley** [comment]
I'm also having this issue.

My csv looks like this..
```
CODE,ROOF_SYSTEM_GROUP,ROOF_SYSTEM_NAME,ROOF_SYSTEM
BU,BU,BUR Asphalt,BUR-A
BU,BU,BUR Coal Tar,BUR-C
BU,BU,Inverted Roof Assembly,IRMA
```

**Comment by jansphil** [comment]
I also had the issue. The root cause was the BOM at the beginning of the csv-file.
I resaved the file in normal UTF-8 encoding without BOM and the file could be parsed successfully.

Also see the section in the Readme of the project.

**Comment by freesh** [comment]
Thx @jasnell that solved the problem. :)
