### ISSUE TITLE
[README.md] Missing comma in sample code

### ISSUE THREAD

**Issue by JavaScriptDude** [mafintosh/csv-parser#18]
In README.md you are missing a comma after the newline: '\n' in the block:

var stream = csv({
  raw: false,    // do not decode to utf-8 strings
  separator: ',', // specify optional cell separator
  newline: '\n' // specify a newline character
  headers: ['index', 'message'] // Specifing the headers
})

**Comment by mafintosh** [comment]
Fixed in master now. Thank for reporting this.
