### ISSUE TITLE
Extra quotes around space between separators and quotes

### ISSUE THREAD

**Issue by quantuminformation** [mafintosh/csv-parser#180]
* Operating System: Mac 10.15.1
* Node Version: 12.13.1
* NPM Version: 6.12.1
* csv-parser Version:         "csv-parser": "^2.3.3",

### Expected Behavior
when loading this data

csv:
```
"Country","Alpha-2 code","Alpha-3 code","Numeric code","Latitude (average)","Longitude (average)"
"Afghanistan", "AF", "AFG", "4", "33", "65"
"Albania", "AL", "ALB", "8", "41", "20"
```

I expect no extra space and quotes the in ["Alpha-3 code"] data, the same as is correctly parsed with `item.Country`

### Actual Behavior

See: 

![image](https://user-images.githubusercontent.com/216566/92718674-68463e80-f362-11ea-84f5-60e709d09bf7.png)

### How Do We Reproduce?
try parse the csv example with

```js
 fs.createReadStream(path.resolve(__dirname, `../rawData/${fileName}`))
        .pipe(csv())
        .on("data", (data) => results.push(data))
        .on("end", async () => {
            await Promise.all(
                results.map((item) =>
                    addDbRow("countries/", item["Alpha-3 code"], { country: item.Country })
                )
            )
            console.log("All promises resolved")
        })```

**Comment by quantuminformation** [comment]
Looking this further appears that it doesn't parse the space correctly 

`"Afghanistan", "AF"`

**Comment by shellscape** [comment]
The structure of.your CSV rows is bad. Eliminate the spaces between the quoted value and the commas and you won't have an issue. You can reference the CSV spec for more info. Other packages may handle this more elegantly, but you should always strive for a valid file.

**Comment by quantuminformation** [comment]
Yeh, makes sense. I uploaded to g docs and redownloaded and it is fine, thx.
