### ISSUE TITLE
skipLines from-to

### ISSUE THREAD

**Issue by LMJayasundara** [mafintosh/csv-parser#185]
Good job nice library ever  made for Node.js,
Thank you.

I have some smaller questions.
How to skip specific lines using this library

Ex when I have 100 lines of CSV
How to skip the last 20 lines or skip from 80 to 100

Can anyone give an idea
Thank you

**Comment by shellscape** [comment]
Keep count in the `data` handler. https://github.com/mafintosh/csv-parser#data

**Comment by LMJayasundara** [comment]
can you give some example code? 
(I am new to js 😍)

**Comment by shellscape** [comment]
I would suggest trying an online bootcamp or a Nice fundamentals course from Wes Bos.

**Comment by conartist6** [comment]
If you don't know Javascript this is probably not the parser you want. You want [this](https://csv.js.org/parse/api/sync/) It will be much easier to work with, and you can just write `records.slice(80, 100)` if that's what you need.

**Comment by LMJayasundara** [comment]
> Keep count in the `data` handler. https://github.com/mafintosh/csv-parser#data

It is not suitable 
have to add  slice function to lib like this

```
fs.createReadStream('data.csv')
  .pipe(csv({
       slice(80, 100)
    }))

```
