### ISSUE TITLE
Doesn't work within Docker, while correctly runs on Local

### ISSUE THREAD

**Issue by Jigar3** [mafintosh/csv-parser#189]
* Operating System: Arch Linux
* Node Version: v12.13.0 (Local Machine), Docker (node:12.2.0-alpine)
* NPM Version:6.12.0
* csv-parser Version: 3.0.0

### Expected Behavior
Running on Docker should return the same result.

### Actual Behavior
While running on Docker, the promise Rejects, instead of resolving with the correct values. It works fine on the local machine I am running on.

### How Do We Reproduce?
```
import csv from 'csv-parser';
import { Readable } from 'stream';

const parseCSVToJSON = (csvString: string) => {
    return new Promise((resolve, reject) => {
        logger.info(csvString);
        const results: Array<any> = [];
        Readable.from([csvString])
            .pipe(csv())
            .on('data', (data) => results.push(data))
            .on('end', () => {
                logger.info(results);
                if (results.length == 0) { reject([]); }
                else { resolve(results); }
            });
    });
};
```
This is the function I am using and calling it like below
```
const parsedData = await parseCSVToJSON(keyDrivers.toString()).catch(err => {
        return res.json({ args: req.body, data: '', err: err });
    });

return res.json({ args: req.body, data: parsedData });
```

So, on my local machine, I correctly get the response, but on Docker, I get the response of the catch block.

Any ideas why this might be happening? Any help appreciated.

**Comment by Jigar3** [comment]
I was able to fix this by using the same Node version on Docker, but still would like to know why was it not working v12.2.0

**Comment by TrySound** [comment]
Hi. With what promise rejects? 12.2 is very old version and may contain bugs. Better upgrade to the latest lts.

**Comment by Jigar3** [comment]
The promise rejects with empty object

**Comment by TrySound** [comment]
I would use [get-stream](https://github.com/sindresorhus/get-stream) to convert stream to promise. Streams are tricky to handle properly.

**Comment by Jigar3** [comment]
Cool, thanks. You can close this issue.
