### ISSUE TITLE
strict: no documentation about row length when strict is enabled

### ISSUE THREAD

**Issue by vicradon** [mafintosh/csv-parser#190]
Documentation Is:

- [x] Missing
- [x] Needed
- [ ] Confusing
- [ ] Not Sure?

### Please Explain in Detail...
When strict is set to true and the headers supplied are less than the number of headers in the CSV, this error is thrown
```
RangeError: Row length does not match headers
    at CsvParser.parseLine (/home/runner/TakeHome/node_modules/csv-parser/index.js:163:17)
    at CsvParser._transform (/home/runner/TakeHome/node_modules/csv-parser/index.js:252:16)
```
For example, given this CSV
```
First name,Last name
Mocha,Chai
React,Redux
```
Supplying this data
```js
    const results = await neatCsv(csvData, { separator: ",", skipLines: 1, strict: true, headers: ["First name"]  })
```
throws the error.

### Your Proposal for Changes
Some more documentation on what should be included when strict is set to true.

**Comment by TrySound** [comment]
You pass only one header in options. This leads to the error.

**Comment by vicradon** [comment]
@TrySound 
Must all available headers be passed?

**Comment by TrySound** [comment]
csv-parser uses either provided headers or passed via options. Strict flag in both cases requires headers count to match columns in each row. From your example it looks like the first row is already a header so you can just remove `headers` option.

**Comment by vicradon** [comment]
Alright, thanks
