### ISSUE TITLE
PR for including the original line in the Error

### ISSUE THREAD

**Issue by basaran** [mafintosh/csv-parser#193]
* Operating System: WSL
* Node Version: 15.8
* NPM Version: 7.5.1
* csv-parser Version: 3.0.0

### Expected Behavior / Situation

CSV is arguably one of the most untrusted file formats passing through the network stack. Parsing errors are common. The error object should include the actual row so that the parser logic can do something with it (write to a file for the user download, so they can see which lines went south)

### Actual Behavior / Situation
At the moment, the error object returned by `csv-parser` does not include the original row.

### Modification Proposal

```
162     if (!skip && this.options.strict && cells.length !== this.headers.length) {
163       const e = new RangeError('Row length does not match headers')
164       e.cells = cells;
165       this.emit('error', e)
166     } else {
167       if (!skip) this.writeRow(cells)
168     }
```

**Comment by TrySound** [comment]
Hi, could you provide exact use case for exposing `cells`? Maybe provide more descriptive error message with line?

**Comment by basaran** [comment]
Hello, I'm intending to create an output file of all the lines I `rejected` through the parsing operation. Including the `csv-parser` pipe.

My pipeline looks something like this:

```
readstream,
csvParserToGiveMeNiceJsonAfterSomeHeaderManipulationAndFiltering, 
on.error,
aTransformationToValidateReturnedJsonSchemaWithJoiThatMightDoAsyncLater
on.error
on.data
writeToSQLfile
```

So, in the end, I should have an SQL importable file. I was also going to suggest including the original cells in the returned JSON as well. This could also be valuable for certain use cases (when filtering the columns through `mapHeaders`.

I do understand there are benchmarks to keep up with it, so if it's beyond the scope of the csv-parser, I can fork and publish a package for my personal use case.

```
  writeRow (cells) {
    ...
    row._cells = cells
    this.push(row)
  }
```

**Comment by sandrooco** [comment]
@TrySound We would really profit from this "feature" too - our use case:
We have a file with around 15'000 lines. It is provided by a third party. Then sometimes our customer tells us that our app is broken because the import doens't work. In reality there's one line in the imported file that makes the import fail. Finding this line is virtually impossible.
This is why we'd love to know what line failed!

Thanks for providing this great library. :)

**Comment by LiamKarlMitchell** [comment]
This is not resolved?
