### ISSUE TITLE
convenience sync api

### ISSUE THREAD

**Issue by maxogden** [mafintosh/csv-parser#20]
e.g. 

```js
require('csv-parser')(csvBuffer) // returns array of parsed objects
```

**Comment by sindresorhus** [comment]
Not sync, but I made a convenience wrapper for non-streaming IO, as that's what I usually deal with:
https://github.com/sindresorhus/neat-csv

**Comment by mafintosh** [comment]
@sindresorhus \o/

**Comment by slang800** [comment]
nice @sindresorhus - probably better to keep any additional APIs in a separate wrapper package too.

**Comment by mafintosh** [comment]
closing this as @sindresorhus fixed it for us :)
