### ISSUE TITLE
`--{before,after}Ouput` and `--outputSeperator` ineffective

### ISSUE THREAD

**Issue by emilbayes** [mafintosh/csv-parser#22]
It seems that this was a planned feature of `ndjson` that never got implemented: https://github.com/maxogden/ndjson/blob/f6184f77d08640f0a67f9b0f7ddb0d1db89e5168/index.js#L26-L30

**Comment by mafintosh** [comment]
the problem was that this broke duplex protocols using ndjson. fx if i do

``` js
var serialize = ndjson.serialize()
var parse = ndjson.parse()

parse.on('data', function (data) {
 console.log(data)
})
serialize.pipe(parse)
serialize.write({hello: 'world'})
```

with your PR the parse stream would never emit any data.

i simple real world use-case of this is https://github.com/mafintosh/rock-paper-scissors-stream which won't work with your pr unfortunately.

**Comment by emilbayes** [comment]
Arr, dang it. Didn't realise. If this is intended behaviour, this should be a test case though :smile:
