### ISSUE TITLE
Is the .on('data') parallel ?

### ISSUE THREAD

**Issue by Darkmagister** [mafintosh/csv-parser#231]
Hello,
i would like to use this awesome lib to parse a csv, i need to manipulate the data, line by line and check if i have that data on the db and update or add it, 
but i would like to know if the .on('data') event are parallel, i mean if i have 2 line that are the same, and on that event i check the db can i be sure that i would see the previous data written on the db or can it be that i will search db while another line is processed and than risk to end up with 2 entry on my db?

is it better to manipulate the line on that event and accumulate it on an array and then in the .on('end') do my stuff with the db?

thanks a lot and sorry for this Issue not issue but more of a support question!

**Comment by mafintosh** [comment]
No problem. The event is sync so its always emitted in order. If you wanna do something async with it, I suggest piping the stream into a writeable stream and impl your async logic in the write method
