### ISSUE TITLE
Trim whitespace in csv headers 

### ISSUE THREAD

**Issue by finnp** [mafintosh/csv-parser#24]
Sometimes the headers include whitespace like

```
a, b , c,  d
1, 2 ,3 , 4
```

In these cases they shouldn't be parsed as `' b'` but be `' b'.trim()` instead.

**Comment by dmlukichev** [comment]
It would be even better if we could specify transform function for headers.
For instance, I have report with following headers: 
['Ship To - Country', 'Ship To - State', 'Ship To - City']. 
But I need: ['country', 'state', 'city'].
I can pass a function that will erase 'Ship To - ' part and lowercase the rest.

**Comment by zommerfelds** [comment]
From the [RFC](https://tools.ietf.org/html/rfc4180):

>  4.  Within the header and each record, there may be one or more
       fields, separated by commas.  Each line should contain the same
       number of fields throughout the file.  Spaces are considered part
       of a field and should not be ignored.  The last field in the
       record must not be followed by a comma.

So maybe that shouldn't be allowed. That being said, the example on the README does actually not work because the header and fields contain spaces.

**Comment by henningBunk** [comment]
I've got a related problem. A header in my csv has the value `Issue ID`. Now when I want to read the according data I cannot acces the field with `data.Issue ID` because of the space. Is there a way to access the field without changing the headers? When not, a custom transform function like proposed fom @dmlukichev would be great.

**Comment by dmlukichev** [comment]
@henningBunk: `data['Issue ID']` doesn't look very pretty, but solves your problem :)

**Comment by henningBunk** [comment]
@dmlukichev Thanks a lot!

**Comment by shellscape** [comment]
Closing, citing comment by @dmlukichev
