### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by vitaly-t** [mafintosh/csv-parser#30]
I have an exported CSV file here with 2.5 bln rows in it, each row at the moment contains only one column of length about 10 symbols.

When I stream it through `fs.createReadStream`, the entire stream finishes processing in 2.4 seconds.

When I redirect the stream into your library, using `.pipe(csv())`, well, I hit Ctrl+Break after 10 mins of it still trying to finish. It is just that slow.

**UPDATE:** I am processing the stream in *paused mode*, and I noticed that once I'm getting `readable` event, the following `read` always returns just one row. This is what seems to create the major bottleneck.

Is it possible to make this library buffer more than one row at a time, so we can make multiple `read`-s on each `readable` to get many rows at once?

**Comment by maxogden** [comment]
@vitaly-t you should try c++

**Comment by vitaly-t** [comment]
@maxogden I think that paying a PC game and then drinking a pint will help me better. But thanks for trying :)

**Comment by maxogden** [comment]
@vitaly-t according to the number in the readme (90,000 rows/second) it would take 7.7 hours to parse 2.5 billion rows

**Comment by vitaly-t** [comment]
@maxogden , that figures. I have updated my question above, pointing at the performance issue.

**Comment by vitaly-t** [comment]
@maxogden on the exact performance figures, I'm getting 43 million rows processed in 1 minute, which isn't as bad as you described, but still, it will take about 1 hour to process the entire file. Next to 2.4 seconds when processing it directly makes you think to use your own CSV parser :)

**Comment by emilbayes** [comment]
Let's consider this a #wontfix unless someone wants to look into it :)

**Comment by vitaly-t** [comment]
@emilbayes have you tried to reproduce the issue described?
