### ISSUE TITLE
null fields

### ISSUE THREAD

**Issue by calvinmetcalf** [mafintosh/csv-parser#31]
certain terrible programs indicate omited fields via shouting null at you instead of just having an empty field, e.g.

| a | b | c | d |
| --- | --- | --- | --- |
| foo | "bar,baz" | NULL | thing |

```
a,b,c,d
foo,"bar,baz",NULL,thing
```

instead of

| a | b | c | d |
| --- | --- | --- | --- |
| foo | "bar,baz" |  | thing |

```
a,b,c,d
foo,"bar,baz",,thing
```

it does understand quoting as fields with a `,` in them are quoted leading me to suspect a field containing the text null in all caps would be rendered as `"NULL"`

**Comment by shellscape** [comment]
@calvinmetcalf what's the result (JSON) when the dataset contains the uppercase `NULL`?
