### ISSUE TITLE
Support for newline characters inside column

### ISSUE THREAD

**Issue by nemo** [mafintosh/csv-parser#34]
Hey folks,

Noticed I couldn't use csv-parser when parsing a file that looks like this:

```
"col1","col2"
"hello","Hey, this is a longe string that has\na few new lines in it\n."
```

Not sure if it's truly valid CSV, but in my experience – it's common practice.

Is there a way to go around this somehow? If not – I may have to modify csv-parser to support this.

**Comment by maxogden** [comment]
for me that parses to this:

```
{"col1":"hello","col2":"Hey, this is a longe string that has\\na few new lines in it\\n."}
```

what do you think it should be parsing to?

**Comment by maxogden** [comment]
Also, if you meant this originally:

```
"col1","col2"
"hello","Hey, this is a longe string that has
a few new lines in it
."
```

that one parses to this:

```
{"col1":"hello","col2":"Hey, this is a longe string that has\na few new lines in it\n."}
```

**Comment by nemo** [comment]
Hm, weird – I was getting a parsing error. May have been the CSV being curropted. I had the people who generate it include each line in a column and that solved my issue.

Let's close this for now – if I run into it again, I'll reopen :)

Thanks for the help!
