### ISSUE TITLE
Column being padded to fixed length

### ISSUE THREAD

**Issue by b3tts32** [mafintosh/csv-parser#38]
I'm parsing a csv file that has an account number column with accounts from lengths ranging from 10 - 12 characters. It appears the parser is padding 0's in from of the records that have 10 or 11 characters. For example 55555555555 is being written as 005555555555. Is there any way to have this written as is? I'm writing the results to mongodb and my find queries aren't returning results due to the mismatch. 

My work around currently is to check if the number starts with a 0 then remove it. This doesn't add too much overhead but I figured I could be missing something. Thanks!

**Comment by maxogden** [comment]
hmm that is weird, I don't believe we should be padding anything, seems like a bug! can you share your csv file to reproduce it?

**Comment by shellscape** [comment]
Closing citing the issue's age. If this is still an issue, please reply with a minimum reproducible CSV file and we'll reopen and investigate. Thanks!
