### ISSUE TITLE
Document the events emitted

### ISSUE THREAD

**Issue by bibhas2** [mafintosh/csv-parser#45]
Currently only the "data" event is documented. Please document all the events that are also emitted. Such as "end", "headers" etc.

**Comment by mafintosh** [comment]
Its a stream so all the stream events are emitted. We should mention headers though I agree. Wanna send a PR for that?

**Comment by bibhas2** [comment]
I made a PR. Thanks.

**Comment by mafintosh** [comment]
fixed by you!
