### ISSUE TITLE
feat: add option to convert string values to numeric values

### ISSUE THREAD

**Issue by germanviscuso** [mafintosh/csv-parser#49]
Inherently there's no data types in a csv, so when each csv row in parsed into a csv object numeric values end up as string values. It would be nice to have an option to convert to numeric values when possible. See: https://www.npmjs.com/package/csvtojson#field-type

**Comment by emilbayes** [comment]
We could consider that. Related to your issue, @mafintosh said that maybe adding a `map` option that intercepts each row might be an option. Otherwise I doing a transform stream is probably your best bet for now

**Comment by slang800** [comment]
I think a separate transform stream should be the standard way to handle this - doing the conversion within csv-parser shouldn't offer any improvement in performance, and just adds bloat/complexity to the package for everyone who doesn't need number type conversion.

If this is a common problem that you run into, you can even make a package dedicated to streaming type conversions, and then require that:

```
process.stdin
  .pipe(csv(args))
  .pipe(castStringsToNumbers('numericFieldOne', 'numericFieldTwo'))
```

Plus, for the CLI you can always do JSON manipulation with jq, like: `cat data.csv | csv-parser | jq ".numericFieldOne |= tonumber | .numericFieldTwo |= tonumber"` (to parse a CSV and convert the `numericFieldOne` & `numericFieldTwo` fields to numbers)

**Comment by shellscape** [comment]
`mapValues` should work for this now. It's not documented on the README, but will be for the 2.0 update.

```js
{
  mapValues: (value) => {
    return isNaN(value) ? value : Number(value)
  }
}
```
