### ISSUE TITLE
Enhancement: allow to plug in custom converters

### ISSUE THREAD

**Issue by germanviscuso** [mafintosh/csv-parser#50]
For example, if I have a column called "Date" with values like:
4/23/12 18:25
I would like to provide a simple converter to have value in the json file look like this:
2012-04-23T18:25:43.511Z

**Comment by emilbayes** [comment]
This is outside the scope of `csv-parser` but you could easily handle this with a transform stream:

```js
const dateConverter = new stream.Transform({
  objectMode: true,
  transform: function (data, enc, cb) {
    data.date = new Date(data.date) // given that we want to transform the date field, and it's something `new Date` understands
    this.push(data)
    cb()
  }
})

process.stdin.pipe(csv()).pipe(dateConverter).pipe(process.stdout)
```
