### ISSUE TITLE
Parsing is not correct ( with special string ) 

### ISSUE THREAD

**Issue by hadson19** [mafintosh/csv-parser#51]
Here is example of data in my CSV file (I got this file from odt, xls).
"FirstName","LastName","countMin", "countMax"
"FirstNameTest","LastNameTest",="01",="01"

So Library Office is nice to open this file, but csv-parser has respond me error.

**Comment by emilbayes** [comment]
So this is not a valid CSV file, and I don't think we'll handle  this issue in `csv-parser`. Is it because you exported with formulas and not with the resolved values?
