### ISSUE TITLE
Enhancement: Add option for unescaped quotes in csv

### ISSUE THREAD

**Issue by yoitsro** [mafintosh/csv-parser#6]
See here: https://github.com/maxogden/binary-csv/issues/7.

Basic idea: allow unescaped quotes to compensate for poorly formatted data.

**Comment by galenandrew** [comment]
@yoitsro @maxogden I was dealing with this same issue as a result of bad data in my CSV, so I submitted PR #28 which added support for a _custom escape character_ (released in `v1.8.0`). If you upgrade to the latest version you can get around this by setting the `escape` option to a non-quote character.

For Example:
```javascript
var csv = require('csv-parser')

fs.createReadStream('some-csv-file.csv')
  .pipe(csv({escape: '`'}))
  .on('data', function(data) {
    console.log('row', data)
  })
```

Hope this helps!

**Comment by hmalphettes** [comment]
Here is my take on dealing with invalid csv files where a quote is not closed at the end of the line: an option to force a new row on every new line character.
https://github.com/sutoiku/csv-parser/commit/9ced1681b51bf53a7f8ca59e2fa2b9b16aefb440

It is a bit out of scope as it definitely targets invalid csv files.
Let me know if this is worth turning into a PR.

**Comment by emilbayes** [comment]
@hmalphettes that will break multi-line cells, no?

**Comment by hmalphettes** [comment]
@emilbayes correct.. but only when the option is explicitly set to {multilines: false}
We tell the parser to not do multi-line cells and we gain the tolerance for unclosed quotes.

For my own projects the customer facing unanimously chose to give up on multi-line cells by default.
