### ISSUE TITLE
Not every entries are processed in big CSV files

### ISSUE THREAD

**Issue by pwnsdx** [mafintosh/csv-parser#65]
Hello,

I would like to report that not every entries are processed in big CSV files (when using with pipe at least).

I tried https://github.com/Keyang/node-csvtojson and it now works fine. I recommend you to use it instead.

**Comment by barkerja** [comment]
Yes. This is an issue. I was just working with a CSV that had around 60,000 rows but csv-parser only parsed 50,000. I immediately tried node-csvtojson and it parsed all 60,000 rows.

**Comment by guomo** [comment]
Same issue here. A file that `wc -l ` reports as having 1,301,014 rows only emits 825,922 _on data_ callbacks before it emits _on end_.

**Comment by joaoneto** [comment]
Hi guys,
I have a similar problem. In my case, the **end** event is fired before the last **data** event.

**example.csv**
```csv
"_id","company","sku","title","description","url","price","categories","meta","createdAt","updatedAt"
1,,1,"Produto Verde","Produto Verde","http:/loja.com/produto/1",571,,,,
2,,2,"Produto Vermelho","Produto Vermelho","http:/loja.com/produto/2",8,,,,
3,,3,"Produto Amarelo","Produto Amarelo","http:/loja.com/produto/3",490,,,,
4,,4,"Produto de Metal","Produto de Metal","http:/loja.com/produto/4",744,,,,
5,,5,"Produto de Madeira","Produto de Madeira","http:/loja.com/produto/5",214,,,,
```

**import.js**
```javascript
const fs = require('fs');
const csv = require('csv-parser');

let productsStream = fs.createReadStream('./example.csv')
  .pipe(csv())
  .on('data', function (data) {
    productsStream.pause();
    // simulate some async
    setTimeout(() => {
      console.log('PRODUCT:', data.title);
      productsStream.resume();
    }, 10);
  })
  .on('end', () => {
    console.log('THE END')
  });
```

**Comment by shellscape** [comment]
Closing given the issue age and the several workarounds mentioned. If this pops up as an issue again and none of the workarounds apply, please open a new issue with a link to sample data that can be used to reproduce the issue.
