### ISSUE TITLE
Support multi-byte newlines

### ISSUE THREAD

**Issue by andrewcurioso** [mafintosh/csv-parser#68]
Right now there is no way to support non standard multi-byte line endings because `newline` is treated as only a single character.

**Comment by mafintosh** [comment]
this already supports windows newlines. did that not work for you?

**Comment by andrewcurioso** [comment]
@mafintosh Unfortunately I have a file with a non-standard newline sequence. Specifically: `\r\r\n`.

I ended up having to set my newline character as `\n` and manually trim the remaining `\r\r` off the end of the last column of each line.

I know it is a bit of strange use case. And unfortunately in this case I can't go back to the app that created the file and ask them to change it. But it would be great if the parser code was generic enough to handle it.

**Comment by andrewcurioso** [comment]
@mafintosh I updated my comment. I said "Windows Style" in my origional message but that wasn't accurate.

**Comment by shinnn** [comment]
IMHO this doesn't seems to the feature that csv-parser should have.

The smartest solution is:

1. Create a new npm module `normalize-newline-stream`.
2. Pipe the CSV data stream to `normalize-newline-stream` before piping it to `csv-parser`.

**Comment by shellscape** [comment]
The `newline` option should support this scenario. If it doesn't work properly, please let us know.
