### ISSUE TITLE
Reread csv on 'end'

### ISSUE THREAD

**Issue by dan-ryan** [mafintosh/csv-parser#71]
How do I reread the csv file on the 'end' function? 

```
fs.createReadStream('data.csv')
    .pipe(stream)
    .on('data', function (data) {
    //do something
    }).on('end', function () {
    //How do I reread the csv again
    });
```

**Comment by mafintosh** [comment]
You would just have to run the pipeline again

**Comment by zammbi** [comment]
I found this solution. Will this cause any issues?

```
function parseData() {
    var stream = csv({
        strict: true,  
        headers: ['timestamp', 'price', 'traded'] 
    });

    fs.createReadStream('data.csv')
        .pipe(stream)
        .on('data', (data) => {
        }).on('end', () => {
            parseData();
        });
}
```

**Comment by alnorth** [comment]
@zammbi Surely that just keeps looping forever?

**Comment by zammbi** [comment]
That is what I wanted at the time. But I found this way to be a little buggy when I actually wanted to stop if I recall.

**Comment by shellscape** [comment]
@dan-ryan what's the end-goal of the scenario that the question was for?

**Comment by dan-ryan** [comment]
At the time, it was to make sure what solution I had was correct. But I found the solution really buggy when stopping. So you probably want to fix that I guess? Otherwise, close this bug.

**Comment by shellscape** [comment]
Hm I'm still not sure I understand what you're attempting to solve with this scenario. There's a disconnect between why you'd want to endlessly and recursively loop through parsing using `end`, and whether or not that's a valid case that the module needs to consider. Personally I can't think of any reason one would want to do that, even for validation. So I suppose it would be helpful to have a thorough explanation of the use-case there.

**Comment by dan-ryan** [comment]
Oh right. The reason why I wanted to continue to loop was because the data file was massive so I couldn't load it all in memory. I needed to continue to read through the data because I was training a neural network.

**Comment by shellscape** [comment]
Going to close this one as stale. For folks in the same scenario, the stream should be broken up into logical blocks for reading according to needs, or wrapped for additional subsequent processing. This module isn't setup for continuous/recursive processing.
