### ISSUE TITLE
how to skip processing of other events like data?

### ISSUE THREAD

**Issue by bhuvans-cyb** [mafintosh/csv-parser#76]
Hi ,
 I have a code which make use of csv-parser and validates the csv file. I'm not using the strict:true option. I'm checking some checks with the headers(like valid headers which my application expects) and parse data in data event etc. However, Can you please let me know how to skip processing data event when I see some error in "header" event?

Ex: `fileStream.pipe(csv())
.on('headers', (headers) => {
}).
on('data',(data) => {
}).
on('end', () => {
});`

**Comment by mafintosh** [comment]
just destroy the stream

```
fileStream.destroy()
// or
fileStream.destroy(new Error('bad headers'))
```

**Comment by bhuvans-cyb** [comment]
[largeCSV.txt](https://github.com/mafintosh/csv-parser/files/1341919/largeCSV.txt)
Thank you . This helped in destroying the stream. I'm facing another issue where in I'm not able to parse entire csv file. Sometimes it is reading only 3k lines out of 8k lines file and sometimes it is reading only 6.5k lines of 10k lines file(which is of 220kb). Please find attached sample file(rename txt extension to csv) which I use. Also, below is the code snippet:

```
fileStream.pipe(csv())
 .on('headers', (headers) => {
  console.log('headers', headers);
})
.on('data', (data) => {
_.each(_.keys(data), (key) => {
   if(_.isEmpty(data[key])) {
  console.log('key: ', key ,' has empty value');
});
})
.

on('end',() => {});
 ```

**Comment by bhuvans-cyb** [comment]
Also, I noticed on testing multiple files, that I'm able to process only files of size  < 130KB only. If I give a larger file, it processes only rows upto that limit and keeps on hanging and finally I get a no response error. Do you know if there is any specific setting to be set to process large files?

**Comment by bhuvans-cyb** [comment]
Sorry.Not the issue with csv-parser. I'm facing backpressure problem when streaming the data and hence I'm able to read only 128kb. Will fix it separately. However, thanks for the help on the stream.destroy(). This issue can be closed.
