### ISSUE TITLE
CSV with utf-16le not parse properly

### ISSUE THREAD

**Issue by finnp** [mafintosh/csv-parser#8]
Hi there,

I totally hate encodings. I had a csv in utf16-le, that produced weird output when piping it into csv-parser (like `\u0000o\u0000r\u0000 \u0000t\u0000h\u0000e\u0000`). I could solve it by encoding the file to utf-8. However maybe there is a way that it will also work for this encoding. I will look into this.

Best,
Finn

**Comment by russmatney** [comment]
@finnp thank you so much for to-utf-8! Ran into exactly this and it works great, saved me a ton of time + headache today!

**Comment by emilbayes** [comment]
FYI `iconv -f utf-16le -t utf-u` is probably better suited. There's also [`iconv-lite`](https://www.npmjs.com/package/iconv-lite) and [`iconv`](https://www.npmjs.com/package/iconv)
