### ISSUE TITLE
Files with absurdly long rows eat up CPU for 14+ hours

### ISSUE THREAD

**Issue by jbreckman** [mafintosh/csv-parser#81]
I know this is kinda silly, but we basically got DOS'd by `csv-parser` last night.

We use `csv-parser` for reading whatever CSV files get uploaded to us.  One such file was malformed so that it only had two lines.  They forgot to include newline separators between rows of data.  Line 1 was a header with 3 columns.  Line 2 was 800mb of text.

Making things worse, we pipe the contents into `csv-parser` from the network.  They seem to come in 1000 byte packets.  It looks like `_transform` is adding the packet to `buf`.  To make the problem clear, once it gets to 400mb in the `buf`, it is going to allocate and deallocate 400+mb about 400,000 times.

I will try to create a PR if I have time, but wanted to get this ticket out there since it's a DOS vulnerability and somewhat hard to protect against without modifications to the library.

**Comment by shellscape** [comment]
A PR was opened to resolve this in #82. However, #83 might have resolved this. #82 was closed due to inactivity. Closing this along with #82.
