### ISSUE TITLE
Option to skip first line when using "headers" option

### ISSUE THREAD

**Issue by erhhung** [mafintosh/csv-parser#84]
I have a CSV file with very descriptive column headers, e.g. "First Name", "Country of Residence", etc, so I use the "**headers**" option to the `csv()` constructor to specify shorter names, e.g. "first" and "country". However, doing so **causes the first line to be emitted as actual data**. Can we add a "`skipFirstLine`" option to prevent this?

**Comment by guomo** [comment]
+1 but for different reasons. There seems to be no legitimate use case to emit the first row of headers when there is a headers event emitted already.

**Comment by combizs** [comment]
I have a [PR](https://github.com/mafintosh/csv-parser/pull/111) that fixes the issue of `skipLines` actually skipping when used with `headers`.  Once approved, you can use `skipLines: 1` to skip through the first emitted header.

**Comment by shellscape** [comment]
Implemented in ead4c1f3a14dbdad961231f3685307e78a03b07e
