### ISSUE TITLE
An "headers" field value is overwritten by csv file headers property.

### ISSUE THREAD

**Issue by fgcloutier** [mafintosh/csv-parser#85]
Assuming you have an "headers" csv field, the following code overwrites its values with the file's headers.

https://github.com/mafintosh/csv-parser/blob/d8791d38bc79a2239ede843bc352bf78ba92eebf/index.js#L185-L192

I strongly suggest leaving the _Row.prototype safe from any additional property.

**Comment by shellscape** [comment]
@fgcloutier are you stating that the `headers` options is overwritten by headers in a data file?

**Comment by shellscape** [comment]
Closing as stale.
