### ISSUE TITLE
Transform headers

### ISSUE THREAD

**Issue by Kikobeats** [mafintosh/csv-parser#93]
The headers autodetection is super neat but in my case, I need to transform it.

Why do you think about supporting for this passing a function at `headers`?

```
{
 headers: value => value.toLowerCase()
}
```

**Comment by shellscape** [comment]
The README for the 1.x versions haven't been updated, but `mapHeaders` already exists for that purpose and is available in 1.x. However, I would recommend trying the 2.0 beta by installing `npm install csv-parser@beta` and you can view the readme for that version here https://github.com/mafintosh/csv-parser/tree/v2.0#mapheaders

We'll be releasing that as a stable version soon.

**Comment by Kikobeats** [comment]
awesome, thanks!
