### ISSUE TITLE
Add types for TypeScript

### ISSUE THREAD

**Issue by BenjD90** [mafintosh/csv-parser#94]
### Feature Proposal
Add types declaration for this library :
@types/csv-parser
or add
index.d.ts

### Feature Use Case
As a csv-parser integrator, I can have types linked to help me and allow typescript to check if I integrate it well.

thanks

**Comment by shellscape** [comment]
Would be happy to accept a PR that adds types.

**Comment by shellscape** [comment]
Resolved in #104
