### ISSUE TITLE
Array of Arrays as result possible?

### ISSUE THREAD

**Issue by Tilogorn** [mafintosh/csv-parser#95]
* Operating System: Linux Mint 19
* Node Version: 8.12.0
* NPM Version: 6.4.1
* csv-parser Version: 2.0.0

### Expected Behavior / Situation
Setting headers to `false` results in an array of arrays
```js
    [ [
      '8.50',
      '5.575',
      '105.613',
      '0.000',
      '0.000',
      '0',
      '0' ],
    [
      '8.50',
      '5.575',
      '105.613',
      '0.000',
      '0.000',
      '0',
      '0' ] ]
```
### Actual Behavior / Situation
Setting headers to `false` results in an array of `row`s
```js
    [ Row {
        '0': '8.50',
        '1': '5.575',
        '2': '105.613',
        '3': '0.000',
        '4': '0.000',
        '5': '0',
        '6': '0' },
    Row {
        '0': '8.50',
        '1': '5.575',
        '2': '105.613',
        '3': '0.000',
        '4': '0.000',
        '5': '0',
        '6': '0' } ]
```

### Modification Proposal
Possibility to get an array of arrays. The wrapping in an object with keys identically to array indices is unnecessary and results (in my use-case) in parsing them back to a plain array.

**Comment by shellscape** [comment]
That was done for consistency in output. If `headers` is false, row values are the same type. With your expectation, output type would vary. That introduces complexity and has a greater potential for confusion, as users must understand that one setting will result in an array and one setting will result in an object. Sorry, this isn't something we're going to change at this time.

You can however, easily map the results to what you're after with:

```js
const csv = require('csv-parser')
const fs = require('fs')
let results = [];

fs.createReadStream('data.csv')
  .pipe(csv())
  .on('data', results.push)
  .on('end', () => {
     results = results.map(Object.values);
  });
```

**Comment by Tilogorn** [comment]
Understandable, although every other csv-parser I tried does it that way:

`headers: true` -> Array of Objects with key-value
`headers: false` -> Array of Arrays

See for example the two most downloaded csv parsers on npm [csv-parse](https://www.npmjs.com/package/csv-parse) and [papaparse](https://www.npmjs.com/package/papaparse). But no worries, since the user has the choice between different solutions, every approach is welcome :blush: I just wanted to give your solution a try and that irritated me.

Thank you for your code sample showing the mapping!
